server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name lideryprava.ru www.lideryprava.ru 72.56.38.62 _;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;

    server_name lideryprava.ru www.lideryprava.ru;

    ssl_certificate /etc/nginx/ssl/lideryprava-fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lideryprava.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    include /etc/nginx/snippets/agentum-ssl-site.conf;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name 72.56.38.62;

    ssl_certificate /etc/letsencrypt/live/slava-hunter.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/slava-hunter.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    include /etc/nginx/snippets/agentum-ssl-site.conf;
}
